# Generated by Django 3.2.2 on 2021-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=600)),
                ('industry', models.CharField(max_length=600)),
                ('country', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Company_symbol',
            },
        ),
    ]
